//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYLStudio.App.TestConsole.AccountOpening.NaturalPerson {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationOfNaturalPerson", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Middle.Services.AccountOpen" +
        "ing.NaturalPerson")]
    [System.SerializableAttribute()]
    public partial class ApplicationOfNaturalPerson : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ApplyTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApprovedResultTypeEnum> ApprovedResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ApprovedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.BasicInfoOfNaturalPerson BasicInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ContactInfo ContactInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.DigitalDemandSavingsDepositTypeEnum DigitalDemandSavingsDepositTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.InvestigationReport[] InvestigationReportsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ApplyTime {
            get {
                return this.ApplyTimeField;
            }
            set {
                if ((this.ApplyTimeField.Equals(value) != true)) {
                    this.ApplyTimeField = value;
                    this.RaisePropertyChanged("ApplyTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApprovedResultTypeEnum> ApprovedResult {
            get {
                return this.ApprovedResultField;
            }
            set {
                if ((this.ApprovedResultField.Equals(value) != true)) {
                    this.ApprovedResultField = value;
                    this.RaisePropertyChanged("ApprovedResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ApprovedTime {
            get {
                return this.ApprovedTimeField;
            }
            set {
                if ((this.ApprovedTimeField.Equals(value) != true)) {
                    this.ApprovedTimeField = value;
                    this.RaisePropertyChanged("ApprovedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.BasicInfoOfNaturalPerson BasicInfo {
            get {
                return this.BasicInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.BasicInfoField, value) != true)) {
                    this.BasicInfoField = value;
                    this.RaisePropertyChanged("BasicInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ContactInfo ContactInfo {
            get {
                return this.ContactInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactInfoField, value) != true)) {
                    this.ContactInfoField = value;
                    this.RaisePropertyChanged("ContactInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.DigitalDemandSavingsDepositTypeEnum DigitalDemandSavingsDepositType {
            get {
                return this.DigitalDemandSavingsDepositTypeField;
            }
            set {
                if ((this.DigitalDemandSavingsDepositTypeField.Equals(value) != true)) {
                    this.DigitalDemandSavingsDepositTypeField = value;
                    this.RaisePropertyChanged("DigitalDemandSavingsDepositType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.InvestigationReport[] InvestigationReports {
            get {
                return this.InvestigationReportsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestigationReportsField, value) != true)) {
                    this.InvestigationReportsField = value;
                    this.RaisePropertyChanged("InvestigationReports");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicInfoOfNaturalPerson", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Middle.Services.AccountOpen" +
        "ing.NaturalPerson")]
    [System.SerializableAttribute()]
    public partial class BasicInfoOfNaturalPerson : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElementarySchoolNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.GenderTypeEnum GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.IdentityDocument[] IdentityDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.IdentityTypeEnum IdentityTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LegalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ElementarySchoolName {
            get {
                return this.ElementarySchoolNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementarySchoolNameField, value) != true)) {
                    this.ElementarySchoolNameField = value;
                    this.RaisePropertyChanged("ElementarySchoolName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.GenderTypeEnum Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.IdentityDocument[] IdentityDocuments {
            get {
                return this.IdentityDocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityDocumentsField, value) != true)) {
                    this.IdentityDocumentsField = value;
                    this.RaisePropertyChanged("IdentityDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.IdentityTypeEnum IdentityType {
            get {
                return this.IdentityTypeField;
            }
            set {
                if ((this.IdentityTypeField.Equals(value) != true)) {
                    this.IdentityTypeField = value;
                    this.RaisePropertyChanged("IdentityType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LegalDate {
            get {
                return this.LegalDateField;
            }
            set {
                if ((this.LegalDateField.Equals(value) != true)) {
                    this.LegalDateField = value;
                    this.RaisePropertyChanged("LegalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactInfo", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Middle.Services.AccountOpen" +
        "ing.NaturalPerson")]
    [System.SerializableAttribute()]
    public partial class ContactInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AddressInfo[] AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.EmailInfo[] EmailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.PhoneInfo[] PhonesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AddressInfo[] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.EmailInfo[] Emails {
            get {
                return this.EmailsField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailsField, value) != true)) {
                    this.EmailsField = value;
                    this.RaisePropertyChanged("Emails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.PhoneInfo[] Phones {
            get {
                return this.PhonesField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonesField, value) != true)) {
                    this.PhonesField = value;
                    this.RaisePropertyChanged("Phones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApprovedResultTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Models")]
    public enum ApprovedResultTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reject = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DigitalDemandSavingsDepositTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Middle.Services.AccountOpen" +
        "ing.NaturalPerson")]
    public enum DigitalDemandSavingsDepositTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Class1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Class2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Class3 = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvestigationReport", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Middle.Services.AccountOpen" +
        "ing.NaturalPerson")]
    [System.SerializableAttribute()]
    public partial class InvestigationReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.CaseRecord[] CaseRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.CaseRecord[] CaseRecords {
            get {
                return this.CaseRecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseRecordsField, value) != true)) {
                    this.CaseRecordsField = value;
                    this.RaisePropertyChanged("CaseRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenderTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Models")]
    public enum GenderTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityDocument", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Middle.Services.AccountOpen" +
        "ing.NaturalPerson")]
    [System.SerializableAttribute()]
    public partial class IdentityDocument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.IdentityDocumentTypeEnum DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> IssuedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.IssuedTypeEnum> IssuedTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentId {
            get {
                return this.DocumentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentIdField, value) != true)) {
                    this.DocumentIdField = value;
                    this.RaisePropertyChanged("DocumentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.IdentityDocumentTypeEnum DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((this.DocumentTypeField.Equals(value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IssuedDate {
            get {
                return this.IssuedDateField;
            }
            set {
                if ((this.IssuedDateField.Equals(value) != true)) {
                    this.IssuedDateField = value;
                    this.RaisePropertyChanged("IssuedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.IssuedTypeEnum> IssuedType {
            get {
                return this.IssuedTypeField;
            }
            set {
                if ((this.IssuedTypeField.Equals(value) != true)) {
                    this.IssuedTypeField = value;
                    this.RaisePropertyChanged("IssuedType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerId {
            get {
                return this.OwnerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerIdField, value) != true)) {
                    this.OwnerIdField = value;
                    this.RaisePropertyChanged("OwnerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Models")]
    public enum IdentityTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NaturalPerson = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JuridicalPerson = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityDocumentTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Models")]
    public enum IdentityDocumentTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdentificationCard = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HealthInsuranceCard = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DriverLicense = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NaturalPerson = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Passport = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IssuedTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Models")]
    public enum IssuedTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Renewed = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressInfo", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Middle.Services.AccountOpen" +
        "ing.NaturalPerson")]
    [System.SerializableAttribute()]
    public partial class AddressInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AddressTypeEnum AddressTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AddressTypeEnum AddressType {
            get {
                return this.AddressTypeField;
            }
            set {
                if ((this.AddressTypeField.Equals(value) != true)) {
                    this.AddressTypeField = value;
                    this.RaisePropertyChanged("AddressType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailInfo", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Middle.Services.AccountOpen" +
        "ing.NaturalPerson")]
    [System.SerializableAttribute()]
    public partial class EmailInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.EmailUsageTypeEnum UsageTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.EmailUsageTypeEnum UsageType {
            get {
                return this.UsageTypeField;
            }
            set {
                if ((this.UsageTypeField.Equals(value) != true)) {
                    this.UsageTypeField = value;
                    this.RaisePropertyChanged("UsageType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneInfo", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Middle.Services.AccountOpen" +
        "ing.NaturalPerson")]
    [System.SerializableAttribute()]
    public partial class PhoneInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.PhoneTypeEnum PhoneTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.PhoneTypeEnum PhoneType {
            get {
                return this.PhoneTypeField;
            }
            set {
                if ((this.PhoneTypeField.Equals(value) != true)) {
                    this.PhoneTypeField = value;
                    this.RaisePropertyChanged("PhoneType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Models")]
    public enum AddressTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Household = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Residence = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Company = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PostBox = 4096,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailUsageTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Models")]
    public enum EmailUsageTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ntd = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fund = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fe = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gold = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ecc = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Models")]
    public enum PhoneTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Home = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Company = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fax = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cellphone = 4096,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HomeAndCompany = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HomeAndFax = 257,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyAndFax = 272,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseRecord", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Middle.Services.AccountOpen" +
        "ing.NaturalPerson")]
    [System.SerializableAttribute()]
    public partial class CaseRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RecordTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseId {
            get {
                return this.CaseIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseIdField, value) != true)) {
                    this.CaseIdField = value;
                    this.RaisePropertyChanged("CaseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RecordTime {
            get {
                return this.RecordTimeField;
            }
            set {
                if ((this.RecordTimeField.Equals(value) != true)) {
                    this.RecordTimeField = value;
                    this.RaisePropertyChanged("RecordTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountOpeningServiceResult", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Middle.Services.AccountOpen" +
        "ing.NaturalPerson")]
    [System.SerializableAttribute()]
    public partial class AccountOpeningServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.StepTypeEnum, bool> CompletedStepsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.StepTypeEnum NextStepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.StepTypeEnum PreviousStepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.OpeningStatusEnum StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.StepTypeEnum, bool> CompletedSteps {
            get {
                return this.CompletedStepsField;
            }
            set {
                if ((object.ReferenceEquals(this.CompletedStepsField, value) != true)) {
                    this.CompletedStepsField = value;
                    this.RaisePropertyChanged("CompletedSteps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.StepTypeEnum NextStep {
            get {
                return this.NextStepField;
            }
            set {
                if ((this.NextStepField.Equals(value) != true)) {
                    this.NextStepField = value;
                    this.RaisePropertyChanged("NextStep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.StepTypeEnum PreviousStep {
            get {
                return this.PreviousStepField;
            }
            set {
                if ((this.PreviousStepField.Equals(value) != true)) {
                    this.PreviousStepField = value;
                    this.RaisePropertyChanged("PreviousStep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.OpeningStatusEnum Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StepTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Services.AccountOpening")]
    public enum StepTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SubmitBasicInfo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SubmitContactInfo = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SubmitQuestionnaire = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadDocument = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Done = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpeningStatusEnum", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Services.AccountOpening")]
    public enum OpeningStatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Applying = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reject = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Middle.Services")]
    public enum CheckTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Storage = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Networking = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByServiceFeature = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 273,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountOpeningServiceChecking", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Middle.Services.AccountOpen" +
        "ing")]
    [System.SerializableAttribute()]
    public partial class AccountOpeningServiceChecking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReplyTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ServiceStatusEnum StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReplyTime {
            get {
                return this.ReplyTimeField;
            }
            set {
                if ((this.ReplyTimeField.Equals(value) != true)) {
                    this.ReplyTimeField = value;
                    this.RaisePropertyChanged("ReplyTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ServiceStatusEnum Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceStatusEnum", Namespace="http://schemas.datacontract.org/2004/07/LYLStudio.App.Services")]
    public enum ServiceStatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Available = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unreachable = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnderMaintenance = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountOpening.NaturalPerson.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Apply", ReplyAction="http://tempuri.org/IService/ApplyResponse")]
        LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult Apply(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson application);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Apply", ReplyAction="http://tempuri.org/IService/ApplyResponse")]
        System.Threading.Tasks.Task<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult> ApplyAsync(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson application);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Cancel", ReplyAction="http://tempuri.org/IService/CancelResponse")]
        LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult Cancel(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson application);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Cancel", ReplyAction="http://tempuri.org/IService/CancelResponse")]
        System.Threading.Tasks.Task<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult> CancelAsync(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson application);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Keep", ReplyAction="http://tempuri.org/IService/KeepResponse")]
        LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult Keep(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson application);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Keep", ReplyAction="http://tempuri.org/IService/KeepResponse")]
        System.Threading.Tasks.Task<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult> KeepAsync(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson application);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Query", ReplyAction="http://tempuri.org/IService/QueryResponse")]
        LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult Query(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.BasicInfoOfNaturalPerson basicInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Query", ReplyAction="http://tempuri.org/IService/QueryResponse")]
        System.Threading.Tasks.Task<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult> QueryAsync(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.BasicInfoOfNaturalPerson basicInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckService", ReplyAction="http://tempuri.org/IService/CheckServiceResponse")]
        LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceChecking CheckService(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.CheckTypeEnum checkType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckService", ReplyAction="http://tempuri.org/IService/CheckServiceResponse")]
        System.Threading.Tasks.Task<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceChecking> CheckServiceAsync(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.CheckTypeEnum checkType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.IService>, LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult Apply(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson application) {
            return base.Channel.Apply(application);
        }
        
        public System.Threading.Tasks.Task<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult> ApplyAsync(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson application) {
            return base.Channel.ApplyAsync(application);
        }
        
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult Cancel(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson application) {
            return base.Channel.Cancel(application);
        }
        
        public System.Threading.Tasks.Task<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult> CancelAsync(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson application) {
            return base.Channel.CancelAsync(application);
        }
        
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult Keep(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson application) {
            return base.Channel.Keep(application);
        }
        
        public System.Threading.Tasks.Task<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult> KeepAsync(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.ApplicationOfNaturalPerson application) {
            return base.Channel.KeepAsync(application);
        }
        
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult Query(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.BasicInfoOfNaturalPerson basicInfo) {
            return base.Channel.Query(basicInfo);
        }
        
        public System.Threading.Tasks.Task<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceResult> QueryAsync(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.BasicInfoOfNaturalPerson basicInfo) {
            return base.Channel.QueryAsync(basicInfo);
        }
        
        public LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceChecking CheckService(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.CheckTypeEnum checkType) {
            return base.Channel.CheckService(checkType);
        }
        
        public System.Threading.Tasks.Task<LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.AccountOpeningServiceChecking> CheckServiceAsync(LYLStudio.App.TestConsole.AccountOpening.NaturalPerson.CheckTypeEnum checkType) {
            return base.Channel.CheckServiceAsync(checkType);
        }
    }
}
